### ISSUE TITLE
Add sambamba to improve the efficiency 

### ISSUE THREAD

**Issue by likelet** [nf-core/EAGER2#14]
May have a think of using sambamba to do sam/bam/cram operation like what I did in [LncPipe](https://github.com/likelet/LncPipe)
for sam->bam conversion 
https://github.com/likelet/LncPipe/blob/master/LncRNAanalysisPipe.nf#L592
and bam sort 
https://github.com/likelet/LncPipe/blob/master/LncRNAanalysisPipe.nf#L593

hope it helps

**Comment by apeltzer** [comment]
Is that still a major speed improvement compared to Samtools 1.8? IIRC, Samtools/HTSjdk etc werde updated and parallelized more (which they weren't when sambamba came out). So this could already be negligible... Thanks for the tip though!

**Comment by likelet** [comment]
sorry, i did not do the comparison between samtools 1.8 and sambamba, i will try it later. 
:)
